'use client'
import React, { useState, useEffect } from 'react';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [windowWidth, setWindowWidth] = useState<number>(0);

  useEffect(() => {
    // Function to update state with window width
    const updateWindowWidth = () => {
      setWindowWidth(window.innerWidth);
    };

    // Update width on mount
    updateWindowWidth();

    // Add event listener for window resize
    window.addEventListener('resize', updateWindowWidth);

    // Cleanup event listener
    return () => window.removeEventListener('resize', updateWindowWidth);
  }, []);

  // Conditionally render based on window width
  if (windowWidth < 1024) { // Assuming tablet breakpoint at 1024px
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', backgroundColor: 'white' }}>
        Please open this application in a Desktop browser for the best experience.
      </div>
    );
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full">
          <SideBar/>
          {children}
        </div>
      </body>
    </html>
  );
}