'use client'
import React, { useState, useEffect } from 'react';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Conditionally render based on window width


  return (
    <html lang="en">
      <body className={`${inter.className} `} >
        <div className='lg:hidden flex justify-center items-center bg-white h-screen'>
          <p className='text-black font-semibold'>Please open it in desktop only.</p>
        </div>
        <div className='lg:flex hidden h-full overflow-x-hidden '>
          <SideBar/>
          {children}
        </div>
        
      </body>
    </html>
  );
}